// Each term: { id, en, kn, category }
const TERMS = [
  // Greetings (common conversation)
  { en: "Hello", kn: "Namaskāra", category: "Common conversation" },
  {
    en: "How are you?",
    kn: "Hēgiddīra?",
    category: "Common conversation",
  },
  {
    en: "I am fine",
    kn: "Nānu chennāgidde",
    category: "Common conversation",
  },
  { en: "Thank you", kn: "Dhanyavāda", category: "Common conversation" },
  {
    en: "Goodbye",
    kn: "Hōguttēne / Hōgi banni",
    category: "Common conversation",
  },
  {
    en: "How is your family?",
    kn: "Nimma kutumba hegide?",
    category: "Common conversation",
  },
  {
    en: "Where do you work?",
    kn: "Nīvu elli kelasa māḍuttīri?",
    category: "Common conversation",
  },
  {
    en: "The weather is good today",
    kn: "Ivattina havamana chennāgide",
    category: "Common conversation",
  },
  {
    en: "I like Karnataka",
    kn: "Nānu Karnataka iṣṭa",
    category: "Common conversation",
  },
  {
    en: "Kannada is a beautiful language",
    kn: "Kannaḍa bahala sundara bhāṣe",
    category: "Common conversation",
  },
  {
    en: "Which sport do you like?",
    kn: "Nimage yāva āṭa iṣṭa?",
    category: "Common conversation",
  },
  {
    en: "See you tomorrow",
    kn: "Nāḷe sigōṇa",
    category: "Common conversation",
  },
  {
    en: "It's very tasty",
    kn: "Tumba ruchiāgide",
    category: "Common conversation",
  },
  { en: "It's enough", kn: "Sākāgide", category: "Common conversation" },

  {
    en: "Where are you from?",
    kn: "Nīvu ellinda?",
    category: "Common conversation",
  },
  { en: "Say that again", kn: "Matte hēḷi", category: "Common conversation" },
  {
    en: "I don't understand",
    kn: "Nānu artha māḍikoḷḷalilla",
    category: "Common conversation",
  },
  {
    en: "Please speak slowly",
    kn: "Dayaviṭṭu nidānāvāgi māthāḍi",
    category: "Common conversation",
  },
  {
    en: "What is your name?",
    kn: "Nimma hesaru ēnu?",
    category: "Common conversation",
  },
  { en: "My name is -", kn: "Nanna hesaru -", category: "Common conversation" },
  { en: "Good day", kn: "Shubha dina", category: "Common conversation" },
  { en: "Good Evening", kn: "Shubha Sanje", category: "Common conversation" },
  { en: "Excuse me/Sorry", kn: "Kṣamisi", category: "Common conversation" },
  {
    en: "No problem/You're welcome",
    kn: "Ēnu bēḍa",
    category: "Common conversation",
  },
  { en: "Dayavittu", kn: "Please", category: "Common conversation" },
  { en: "Yes", kn: "Howdu", category: "Common conversation" },
  { en: "No", kn: "Illa", category: "Common conversation" },
  { en: "I Want", kn: "Beka", category: "Common conversation" },
  { en: "I Don't Want", kn: "Beda", category: "Common conversation" },
  { en: "Do you want?", kn: "Beku?", category: "Common conversation" },
  {
    en: "Where are you going?",
    kn: "nīvu elli hōguttiddīri??",
    category: "Common conversation",
  },
  {
    en: "I am going to - ",
    kn: "nānu - hōguttiddēne",
    category: "Common conversation",
    },
    { en: "Where are they?", kn: "Avaru ellidare?", category: "Common conversation" },
      { en: "They are here", kn: "Avaru illidare", category: "Common conversation" },

  // Directions (common conversation)
  { en: "How far?", kn: "Eṣṭu dūra?", category: "Common conversation" },
  { en: "Right", kn: "Balake", category: "Common conversation" },
  { en: "Left", kn: "Edake", category: "Common conversation" },
  { en: "Up", kn: "Meleke", category: "Common conversation" },
  { en: "Down", kn: "Kelage", category: "Common conversation" },
  { en: "Forward", kn: "Mundake", category: "Common conversation" },
  { en: "Backward", kn: "Hindake", category: "Common conversation" },

  // Colors
  { en: "Red", kn: "Kempu", category: "Colors" },
  { en: "Blue", kn: "Neeli", category: "Colors" },
  { en: "Green", kn: "Hasiru", category: "Colors" },
  { en: "Orange", kn: "Kittale", category: "Colors" },
  { en: "Yellow", kn: "Haladi", category: "Colors" },
  { en: "Purple", kn: "Nerale", category: "Colors" },
  { en: "Brown", kn: "Kandu", category: "Colors" },
  { en: "Black", kn: "Kappu", category: "Colors" },
  { en: "White", kn: "Bili", category: "Colors" },
  { en: "Gray", kn: "Budu", category: "Colors" },
  { en: "Pink", kn: "Gulabi", category: "Colors" },
  { en: "Gold", kn: "Suvarna", category: "Colors" },
  { en: "Silver", kn: "Belli", category: "Colors" },
  { en: "Maroon", kn: "Kadugempu", category: "Colors" },
  { en: "Sky Blue", kn: "Akasanili", category: "Colors" },
  { en: "Saffron", kn: "Kesari", category: "Colors" },
  { en: "Dark", kn: "Gaadhavada", category: "Colors" },

  // Numbers
  { en: "1", kn: "Ondu", category: "Numbers" },
  { en: "2", kn: "Eraḍu", category: "Numbers" },
  { en: "3", kn: "Mūru", category: "Numbers" },
  { en: "4", kn: "Nālku", category: "Numbers" },
  { en: "5", kn: "Aidu", category: "Numbers" },
  { en: "6", kn: "Āru", category: "Numbers" },
  { en: "7", kn: "Ēḷu", category: "Numbers" },
  { en: "8", kn: "Enṭu", category: "Numbers" },
  { en: "9", kn: "Ombattu", category: "Numbers" },
  { en: "10", kn: "Hattu", category: "Numbers" },
  { en: "11", kn: "Hannondu", category: "Numbers" },
  { en: "12", kn: "Hanneraḍu", category: "Numbers" },
  { en: "13", kn: "Hadimūru", category: "Numbers" },
  { en: "14", kn: "Hadinālku", category: "Numbers" },
  { en: "15", kn: "Hadinaidu", category: "Numbers" },
  { en: "16", kn: "Hadināru", category: "Numbers" },
  { en: "17", kn: "Hadinēḷu", category: "Numbers" },
  { en: "18", kn: "Hadineṇṭu", category: "Numbers" },
  { en: "19", kn: "Hattombattu", category: "Numbers" },
  { en: "20", kn: "Ippattu", category: "Numbers" },
  { en: "30", kn: "Mūvattu", category: "Numbers" },
  { en: "40", kn: "Nalavattu", category: "Numbers" },
  { en: "50", kn: "Aivattu", category: "Numbers" },
  { en: "60", kn: "Aravattu", category: "Numbers" },
  { en: "70", kn: "Eppattu", category: "Numbers" },
  { en: "80", kn: "Embattu", category: "Numbers" },
  { en: "90", kn: "Tombattu", category: "Numbers" },
  { en: "100", kn: "Nūru", category: "Numbers" },
  { en: "1000", kn: "Sāvira", category: "Numbers" },

  // Body parts
  { en: "Head", kn: "Tale", category: "Body parts" },
  { en: "Hand", kn: "Kai", category: "Body parts" },
  { en: "Eye", kn: "Kannu", category: "Body parts" },
  { en: "Hair", kn: "Koodalu", category: "Body parts" },
  { en: "Forehead", kn: "Hane", category: "Body parts" },
  { en: "Eyebrow", kn: "Hubbu", category: "Body parts" },
  { en: "Eyelid", kn: "Kannu Reppe", category: "Body parts" },
  { en: "Ear", kn: "Kivi", category: "Body parts" },
  { en: "Nose", kn: "Mugu", category: "Body parts" },
  { en: "Cheek", kn: "Kenne", category: "Body parts" },
  { en: "Mouth", kn: "Bayi", category: "Body parts" },
  { en: "Lips", kn: "Tuti", category: "Body parts" },
  { en: "Teeth", kn: "Hallu", category: "Body parts" },
  { en: "Tongue", kn: "Nalige", category: "Body parts" },
  { en: "Chin", kn: "Galla", category: "Body parts" },
  { en: "Beard", kn: "Gadda", category: "Body parts" },
  { en: "Moustache", kn: "Mise", category: "Body parts" },
  { en: "Neck", kn: "Katthu", category: "Body parts" },
  { en: "Shoulder", kn: "Bhuja", category: "Body parts" },
  { en: "Chest", kn: "Ede", category: "Body parts" },
  { en: "Belly", kn: "Hotte", category: "Body parts" },
  { en: "Back", kn: "Bennu", category: "Body parts" },
  { en: "Arm", kn: "Tulu", category: "Body parts" },
  { en: "Elbow", kn: "Mona Kai", category: "Body parts" },
  { en: "Palm", kn: "Angai", category: "Body parts" },
  { en: "Finger", kn: "Beralu", category: "Body parts" },
  { en: "Nail", kn: "Uguru", category: "Body parts" },
  { en: "Wasit/Hip", kn: "Sonta", category: "Body parts" },
  { en: "Thigh", kn: "Thode", category: "Body parts" },
  { en: "Knee", kn: "Mona Kalu", category: "Body parts" },
  { en: "Leg", kn: "Kalu", category: "Body parts" },
  { en: "Foot", kn: "Pada", category: "Body parts" },
  { en: "Ankle", kn: "Gajakattu", category: "Body parts" },
  { en: "Heel", kn: "Himmadi", category: "Body parts" },
  { en: "Toe", kn: "Kalberalu", category: "Body parts" },
  { en: "Bone", kn: "Mule", category: "Body parts" },
  { en: "Skin", kn: "Charma", category: "Body parts" },
  { en: "Blood", kn: "Rakta", category: "Body parts" },
  { en: "Heart", kn: "Hrudaya", category: "Body parts" },
  { en: "Brain", kn: "Midulu", category: "Body parts" },
  { en: "Throat", kn: "Gantalu", category: "Body parts" },
  { en: "Nerve", kn: "Nara", category: "Body parts" },
  { en: "Intestine", kn: "Karulu", category: "Body parts" },

  // Question words
  { en: "What", kn: "Ēnu", category: "Question words" },
  { en: "Where", kn: "Yelli", category: "Question words" },
  { en: "Why", kn: "Yāke", category: "Question words" },
  { en: "Who", kn: "Yāru", category: "Question words" },
  { en: "When", kn: "Yāvāga", category: "Question words" },
  { en: "How", kn: "Hēge", category: "Question words" },
  { en: "How Much", kn: "Eṣṭu", category: "Question words" },

  // Pronouns
  { en: "I", kn: "Nanu", category: "Pronouns" },
  { en: "You", kn: "Ninu", category: "Pronouns" },
  { en: "You (Pl)", kn: "Nivu", category: "Pronouns" },
  { en: "He", kn: "Avanu", category: "Pronouns" },
  { en: "She", kn: "Avalu", category: "Pronouns" },
  { en: "It", kn: "Atu", category: "Pronouns" },
  { en: "We", kn: "Navu", category: "Pronouns" },
  { en: "They", kn: "Avaru", category: "Pronouns" },
  { en: "Me (Obj)", kn: "Nananu", category: "Pronouns" },
  { en: "You (Obj)", kn: "Ninanu", category: "Pronouns" },
  { en: "Him (Obj)", kn: "Avananu", category: "Pronouns" },
  { en: "Her (Obj)", kn: "Avalanu", category: "Pronouns" },
  { en: "Us (Obj)", kn: "Namanu", category: "Pronouns" },
  { en: "Them (Obj)", kn: "Avugalanu", category: "Pronouns" },
  { en: "My (Pos)", kn: "Nana", category: "Pronouns" },
  { en: "Your (Pos)", kn: "Nina", category: "Pronouns" },
  { en: "His (Pos)", kn: "Avana", category: "Pronouns" },
  { en: "Her (Pos)", kn: "Avala", category: "Pronouns" },
  { en: "Our (Pos)", kn: "Namma", category: "Pronouns" },
  { en: "Their (Pos)", kn: "Avara", category: "Pronouns" },
  { en: "Mine", kn: "Nanadu", category: "Pronouns" },
  { en: "Yours", kn: "Nimadu", category: "Pronouns" },
  { en: "His", kn: "Avanadu", category: "Pronouns" },
  { en: "Hers", kn: "Avaladu", category: "Pronouns" },
  { en: "Its", kn: "Atatu", category: "Pronouns" },
  { en: "Ours", kn: "Namadu", category: "Pronouns" },
  { en: "Theirs", kn: "Avaradu", category: "Pronouns" },
  { en: "Himself", kn: "Svata", category: "Pronouns" },
  { en: "Yourself", kn: "Nive", category: "Pronouns" },
  { en: "To me", kn: "Nanage", category: "Pronouns" },
  { en: "To you", kn: "Ninage", category: "Pronouns" },
  { en: "To you (pl)", kn: "Nimage", category: "Pronouns" },
  { en: "To him", kn: "Avanige", category: "Pronouns" },
  { en: "To her", kn: "Avalige", category: "Pronouns" },
  { en: "To them", kn: "Avarige", category: "Pronouns" },
  { en: "Themself", kn: "Avare", category: "Pronouns" },
  { en: "To us", kn: "Namage", category: "Pronouns" },
  { en: "This", kn: "Idu", category: "Pronouns" },
  { en: "That", kn: "Adu", category: "Pronouns" },
  { en: "With/From me", kn: "Naninda", category: "Pronouns" },
  { en: "Along with me", kn: "Nanondige", category: "Pronouns" },
  { en: "In/On me", kn: "Nanali", category: "Pronouns" },
  { en: "These people", kn: "Ivaru", category: "Pronouns" },
  { en: "Those people", kn: "Avaru", category: "Pronouns" },
];

// CaIduat you mentioned (you can add more)
const CATEGORIES = [
  "Body parts",
  "Colors",
  "Household",
  "People",
  "Weather",
  "Numbers",
  "Emotions",
  "Pronouns",
  "Dates and times",
  "Nature and animals",
  "Common conversation",
  "Question words",
];

//{ en: "", kn: "", category: "" },
